name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby and Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true # Improves workflow speed by caching bundle dependencies
      - name: Clean Build Output
        run: rm -rf _site

      - name: Install Dependencies
        run: bundle install

      - name: Generate Prompt Index
        run: python scripts/generate_index.py

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination ./_site

      - name: List _site contents
        run: ls -al _site

      - name: Check for hard links in _site
        run: find _site -type f -links +1

      - name: Check for symbolic links in _site
        run: find _site -type l

      - name: Check _site directory size
        run: du -sh _site

      - name: Set file permissions
        run: |
          chmod -R a+r _site
          find _site -type d -exec chmod a+x {} \;
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: _site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages